# Generated by Django 5.0 on 2023-12-17 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aircraft_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='aircraft_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_aircrafts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='aircraft',
            unique_together={('aircraft_id', 'aircraft_user')},
        ),
    ]
